### ISSUE TITLE
Define API requirements

### ISSUE THREAD

**Issue by tatedean** [bytesandbrews-smtx/roulette-bites#3]
What must these APIs be capable of?
- They must work within our production/development environments
- They must be free or decently affordable
-

**Comment by symbiontik** [comment]
On top of Google Places API and Amazon Locations API, I've looked into quite a few APIs that return POI (point of interest) information from this guide:
- https://traveltime.com/blog/google-places-api-alternatives-points-of-interest-data#1-foursquare-places-api

After reading through the options, it looks like the one that is modern, perpetually free, up-to-date, and best usable for our use-case is Yelp's Fusion API here:
- https://www.yelp.com/developers/faq
- https://docs.developer.yelp.com/docs/fusion-intro
- https://spin.atomicobject.com/2022/01/31/yelp-api-react-native-app/

As a bonus, this will give us experience using GraphQL, a more efficient, modern method for querying APIs compared to REST API format.

**Comment by symbiontik** [comment]
Grabbed us a developer account and API Key so we can experiment with the Yelp API:

Client ID
3vKJY2Ml1cBCdm-6eIMYAA

API Key
9nntrke6fVf6C4oEJzpaF2W419UbQR2CojDf_KDnRfKvjIAqwm3aKvifqhVciLrNP72xUiZDh52CVetmBXqbAt_7zO0PiD8PF00RCKRQT5gNaNU0mqnu3FNjZZucY3Yx

Daily API limit
5000.0 calls

**Comment by symbiontik** [comment]
Also joined the Developer Beta so we can make GraphQL calls (instead of REST API calls):

GraphQL Usage
You are seeing this section because you are currently enrolled in the Developer Beta Program. Please see the [GraphQL Rate Limiting documentation](https://www.yelp.com/developers/graphql/guides/rate_limiting) for details on what 'points' are, how they are calculated, and how they are used to rate-limit access.

Daily Points Limit
250000.0 points

Daily Query Limit
10000.0 queries

**Comment by tatedean** [comment]
We made some progress on successfully returning API data using Powershell. Our local app will not work with the API until we move to a domain name. We'll continue with using Yelp as our designated API as it has all the basic data we need and it's FREE!
